// Shared runtime factory for the colony buildings (brief: style-library/styles/cqs-fleet/briefs/buildings.md).
//
// Every colony building is one GLB (assets/buildings/<id>.glb: node 'hull' = the building baked from the shared kit,
// tools/blender/buildings/bkit.py, plus 'parts_*' = fleet / yard kit parts) and one tiny module src/buildings/<id>.js:
//
//   import { colonyBuilding } from './colony.js';
//   const DATA = {...};   // GENERATED by tools/blender/buildings/colony_build.py: lights, bbox, footprint, orbital
//   export const { meta, asset, studio, load, build } = colonyBuilding({ id, DATA, meta, studio });
//
// registered in ships/index.js BUILDINGS (?mode=building&building=<id>, #<id>). The factory gives every building the
// same look and light language:
//   - light concept paint (correction 27): livery null; the fleet PATINA 'hull' detail at a 6 m tile and the worn
//     finish with the 'building' preset (finish.js: wear at 8 / 36 m, matte 0.8-0.97, grit 0.5 m);
//   - lights (STYLE.md Lights, Installations): 0.3 m amber pins at block corners, plinth edges and legs, slow amber
//     beacons, red 0.4 m obstruction lights on stacks (the only lights[]), 0.6 x 0.14 m door lamps over every kit crew
//     door, amber jamb / corner slits, warm glow boxes behind real window glass (~55 % lit), interior glow (open
//     bays, the pour), kit floodlights with lit lenses and one spot light each;
//   - the dusk studio (like the shipyard): exposure 1.25, key 0.85 (v3), dimmed fill / rim / env, lightscape x1.3; camera hint
//     from the concept (az / el); orbital buildings get a space backdrop and no plinth.
// Phone tier: load() asks for the '.lite' copy (512 px textures, workers and vents dropped: build-artifact.mjs).
import * as THREE from 'three';
import { loadGLB, buildGLBShip } from '../lib/glbship.js';

// fixture colours and sizes shared by every colony building (shipyard.js values: one fixture language)
const C = {
  amber: 'amber', pin: 0.3, beacon: { size: 0.3, pulse: 3.6 }, obstruction: 0.4,
  window: { color: '#ffd29a', radiance: 1.35 }, office: { color: '#ffe2b8', radiance: 1.1 },
  glow: { color: '#ffb766', radiance: 0.42 }, lens: { color: '#fff1dc', radiance: 2.2, size: [0.42, 0.05, 0.26] },
  flood: { color: '#ffdcb0', intensity: 2200, distance: 90, angle: 38, penumbra: 0.7 },
};

// the dusk studio (shipyard's), overridable per building
// the key comes from the front-left in the building's frame (sunaz / sunel), like the concepts' light; the backdrop is the
// concepts' slate dusk (displayed sRGB centre / edge), a little greyer than the ship studio's navy.
// v3 paint calibration (README-colony.md "Paint calibration", tools/buildings/paint-check.py): key 0.5 -> 0.85, fill
// 0.6 -> 0.4, env 0.65 -> 0.45. At key 0.5 even the kit's calibrated panel paint rendered at 0.55-0.8x the concepts'
// light-paint luminance (GrabCut-masked p70-97 band) and the shadows read flat; over all 16 buildings the light band is
// now at a median 0.95x. Buildings dominated by big light roofs or slabs trim `key` in their own hint (0.6-1.15)
export const DUSK = { exposure: 1.25, key: 0.85, fill: 0.4, rim: 0.5, kick: 0.6, env: 0.45, lightscapeGain: 1.3, az: 30, el: 28,
  sunaz: -35, sunel: 42, backdrop: { centre: [60, 67, 82], edge: [20, 23, 31], at: [0.5, 0.55] } };
// orbital megaprojects: black-blue space behind them (displayed sRGB, env/lighting.js backdrop)
export const SPACE_BACKDROP = { centre: [22, 27, 40], edge: [4, 6, 10], at: [0.56, 0.58] };

/** Building-frame light specs (buildGLBShip cfg fields) from a generated DATA.lights block. */
export function lightCfg(L = {}, seed = 71) {
  const patterns = [];
  if (L.pins?.length) patterns.push({ points: L.pins, color: C.amber, size: C.pin, intensity: 1.0, keep: true });
  if (L.beacons?.length) patterns.push({ points: L.beacons, color: C.amber, size: C.beacon.size, intensity: 1.0, pulse: C.beacon.pulse, keep: true });
  for (const s of L.slits || []) {
    patterns.push(s.door
      ? { slit: s.p, u: s.u, n: s.n, len: 0.6, width: 0.14, radiance: 1.4, color: C.amber }
      : { slit: s.p, u: s.u, n: s.n, len: s.len, width: s.width ?? 0.18, radiance: 1.6, color: C.amber, keep: true });
  }
  const box = (p, n, w, h, t = 0.04, lift = 0.03) => {
    const ax = Math.abs(n[0]) > Math.abs(n[2]) ? 'x' : 'z';
    const size = Math.abs(n[1]) > 0.7 ? [w, t, h] : ax === 'x' ? [t, h, w] : [w, h, t];
    return { p: [p[0] + n[0] * lift, p[1] + n[1] * lift, p[2] + n[2] * lift], size };
  };
  const fixtures = [
    ...(L.windows || []).map((w) => ({ ...box(w.p, w.n, w.size[0], w.size[1]), color: (w.office ? C.office : C.window).color, radiance: (w.office ? C.office : C.window).radiance })),
    ...(L.glow || []).map((g) => ({ p: g.p, size: g.size, rotY: g.rotY || 0, color: g.color || C.glow.color, radiance: g.radiance ?? C.glow.radiance })),
    ...(L.lenses || []).map((p) => ({ p, size: C.lens.size, color: C.lens.color, radiance: C.lens.radiance })),
  ];
  const interiorLights = (L.floods || []).map((f) => ({ kind: 'spot', p: f.p, target: f.target, color: C.flood.color, intensity: C.flood.intensity,
    distance: C.flood.distance, angle: C.flood.angle, penumbra: C.flood.penumbra, decay: 2 }))
    // v6: process-glow spill (a furnace hearth, molten runner): warm point lights that light the ground round the glow
    .concat((L.spills || []).map((q) => ({ kind: 'point', p: q.p, color: q.color, intensity: q.intensity, distance: q.distance, decay: 2 })));
  const lights = (L.nav || []).map((p) => ({ p, color: 'red', size: C.obstruction }));
  return { lightscape: { seed, patterns }, fixtures, interiorLights, lights };
}

const shift = (p, c) => [p[0] - c.x, p[1] - c.y, p[2] - c.z];
/** Every building-frame position of a cfg moved by -c (buildGLBShip centres the GLB on its bbox). */
export function shiftCfg(cfg, c) {
  return {
    ...cfg,
    lights: cfg.lights.map((l) => ({ ...l, p: shift(l.p, c) })),
    fixtures: cfg.fixtures.map((f) => ({ ...f, p: shift(f.p, c) })),
    interiorLights: cfg.interiorLights.map((l) => ({ ...l, p: shift(l.p, c), ...(l.target ? { target: shift(l.target, c) } : {}) })),
    lightscape: { ...cfg.lightscape, patterns: cfg.lightscape.patterns.map((q) => ({ ...q, ...(q.points ? { points: q.points.map((p) => shift(p, c)) } : {}), ...(q.slit ? { slit: shift(q.slit, c) } : {}) })) },
  };
}

/**
 * The module exports of one colony building.
 *   id     building id (assets/buildings/<id>.glb)
 *   DATA   the generated block: { lights, bbox, footprint, height, orbital }
 *   meta   { name, designation, gameId, blurb }
 *   studio overrides of the dusk studio (az, el, exposure, key, ..., dist)
 *   materials optional glbship material overrides (by name, 'prefix*' or '*')
 *   extend optional (group, ctx) => void: per-building runtime additions (animated parts, instanced ships)
 */
export function colonyBuilding({ id, DATA = {}, meta = {}, studio = {}, materials = null, extend = null }) {
  const asset = {
    glb: `./assets/buildings/${id}.glb`,
    generator: `tools/blender/buildings/${id}.py on bkit.py (colony_build.py) + tools/blender/assemble.py`,
    concept: null,
    rotate: [0, 0, 0],
    hullNodes: ['hull'],
    livery: null, // light concept paint (correction 27)
    detail: { set: 'hull', tile: 6, normalStrength: 0.4, roughAmount: 0.3, cavity: 0.12 },
    finish: 'building',
    // fal colony components (assets/parts-colony, material 'colony_<part>') are albedo-normalised once at ingest against
    // their source component image (component.py NORM: white balance, chroma, one linear gain, metal cap), which puts their
    // light paint on the kit's 'panel' scale: no runtime lift (v2 lifted every colony_* by 1.25 and some modules by up to
    // 2.5 more). `materials` stays for per-building looks that are not paint calibration.
    materials: { ...(materials || {}) },
  };
  const st = { ...DUSK, ...(DATA.orbital ? { backdrop: SPACE_BACKDROP } : {}), ...studio };
  let GLTF = null;
  async function load() { GLTF = await loadGLB(asset.glb, 'lite'); }
  function build(palette, { library = {} } = {}) {
    if (!GLTF) throw new Error(`${id}: call load() first`);
    const raw = new THREE.Box3().setFromObject(GLTF.scene);
    const centre = raw.getCenter(new THREE.Vector3());
    const cfg = shiftCfg({ name: id, ...asset, length: raw.getSize(new THREE.Vector3()).z, ...lightCfg(DATA.lights) }, centre);
    const g = buildGLBShip(GLTF, cfg, { palette, library });
    g.position.copy(centre); // back to the building frame (plinth top y = 0)
    const rec = g.userData.ship;
    for (const k of ['min', 'max', 'center']) rec.envelope[k].add(centre);
    rec.scaleCorrection = 1;
    const group = new THREE.Group();
    group.name = id;
    group.add(g);
    group.userData.ship = rec;
    group.userData.building = { id, meta, effectTargets: [g], studio: st, footprint: DATA.footprint, height: DATA.height };
    extend?.(group, { palette, library, DATA });
    return group;
  }
  return { meta: { ...meta, footprint: DATA.footprint, height: DATA.height }, asset, studio: st, load, build };
}
