// Deuterium Depot (DEUTERIUM_DEPOT) — colony building v1, cqs-fleet style (brief: style-library/styles/cqs-fleet/briefs/buildings.md).
// Concept: style-library/styles/cqs-fleet/images/buildings/deuterium_depot-concept.jpg (approved, correction 35).
// Built by tools/blender/buildings/deuterium_depot.py on the shared kit (bkit.py) with colony_build.py; the runtime is the
// shared colony factory (colony.js): light paint (livery null), building finish preset, generated lights.
import { colonyBuilding } from './colony.js';

// <GENERATED by tools/blender/buildings/colony_build.py: do not edit by hand>
const DATA = {"lights":{"pins":[[-35.05,-0.17,-27.53],[-36.03,-0.17,-26.55],[-35.05,-0.17,20.53],[-36.03,-0.17,19.55],[35.05,-0.17,-27.53],[36.03,-0.17,-26.55],[35.05,-0.17,20.53],[36.03,-0.17,19.55],[-18.0,-0.17,20.55],[0.0,-0.17,20.55],[18.0,-0.17,20.55],[36.05,-0.17,-11.5],[36.05,-0.17,4.5],[-9.49,1.2,-4.525],[-16.525,1.2,2.51],[-26.475,1.2,2.51],[-33.51,1.2,-4.525],[-33.51,1.2,-14.475],[-26.475,1.2,-21.51],[-16.525,1.2,-21.51],[-9.49,1.2,-14.475],[-21.5,26.6,-9.5],[13.01,1.2,2.475],[5.975,1.2,9.51],[-3.975,1.2,9.51],[-11.01,1.2,2.475],[-11.01,1.2,-7.475],[-3.975,1.2,-14.51],[5.975,1.2,-14.51],[13.01,1.2,-7.475],[1.0,26.6,-2.5],[34.01,1.2,-8.525],[26.975,1.2,-1.49],[17.025,1.2,-1.49],[9.99,1.2,-8.525],[9.99,1.2,-18.475],[17.025,1.2,-25.51],[26.975,1.2,-25.51],[34.01,1.2,-18.475],[22.0,26.6,-13.5],[-28.1,6.6,8.2],[-28.1,6.6,16.8],[-10.9,6.6,8.2],[-10.9,6.6,16.8],[9.9,6.6,6.7],[9.9,6.6,15.3],[27.1,6.6,6.7],[27.1,6.6,15.3],[2.4,0.6,18.4],[-32.293,6.82,-25.293],[32.293,6.82,-25.293],[-32.293,6.82,17.793]],"beacons":[[-19.5,8.2,9.0],[18.5,8.2,7.5]],"nav":[],"slits":[],"windows":[],"glow":[],"floods":[],"lenses":[]},"bbox":[[-36.2,-1.677,-29.09],[36.22,7.04,20.72]],"footprint":[72,48],"height":27.0,"orbital":false};
// </GENERATED>

export const { meta, asset, studio, load, build } = colonyBuilding({
  id: 'deuterium_depot',
  DATA,
  meta: {
    name: 'Deuterium Depot', designation: 'DP-3', gameId: 'DEUTERIUM_DEPOT',
    blurb: 'Pressure storage for the fleet\'s fusion fuel: three 21 m deuterium spheres on braced legs with cobalt equator bands, a ground manifold with valves and transfer lines, two pump houses and a dryer skid, on a 72 x 48 m slab.',
  },
  // the concept's camera: front-left, ~25 deg down
  studio: { az: 30, el: 25 },
});
