// Infrastructure (INFRASTRUCTURE) — colony building v1, cqs-fleet style (brief: style-library/styles/cqs-fleet/briefs/buildings.md).
// Concept: style-library/styles/cqs-fleet/images/buildings/infrastructure-concept.jpg (approved, correction 35).
// Built by tools/blender/buildings/infrastructure.py on the shared kit (bkit.py) with colony_build.py; the runtime is the
// shared colony factory (colony.js): light paint (livery null), building finish preset, generated lights.
import { colonyBuilding } from './colony.js';

// <GENERATED by tools/blender/buildings/colony_build.py: do not edit by hand>
const DATA = {"lights":{"pins":[[52.05,-0.17,35.05],[49.05,-0.17,38.05],[38.05,-0.17,38.05],[38.05,-0.17,49.05],[35.05,-0.17,52.05],[-35.05,-0.17,52.05],[-38.05,-0.17,49.05],[-38.05,-0.17,38.05],[-49.05,-0.17,38.05],[-52.05,-0.17,35.05],[-52.05,-0.17,-35.05],[-49.05,-0.17,-38.05],[-38.05,-0.17,-38.05],[-38.05,-0.17,-49.05],[-35.05,-0.17,-52.05],[35.05,-0.17,-52.05],[38.05,-0.17,-49.05],[38.05,-0.17,-38.05],[49.05,-0.17,-38.05],[52.05,-0.17,-35.05],[30.399,4.8,38.319],[30.293,6.3,39.061],[38.319,4.8,30.399],[39.061,6.3,30.293],[-37.27,5.1,-34.77],[-37.27,5.1,-25.23],[-22.73,5.1,-34.77],[-22.73,5.1,-25.23],[-35.293,6.82,49.293],[49.293,6.82,35.293],[49.293,6.82,-35.293],[-35.293,6.82,-49.293]],"beacons":[[0.0,31.0,0.0],[34.0,25.0,-32.0]],"nav":[[1.5,29.0,-1.0]],"slits":[{"p":[-34.85,3.0,-25.18],"u":[0.0,1.0,0.0],"n":[0.0,0.0,1.0],"len":1.0,"width":0.16,"door":false},{"p":[-30.95,3.0,-25.18],"u":[0.0,1.0,0.0],"n":[0.0,0.0,1.0],"len":1.0,"width":0.16,"door":false},{"p":[-26.4,2.72,-25.5],"u":[1.0,0.0,0.0],"n":[0.0,0.0,1.0],"len":0.6,"width":0.14,"door":true}],"windows":[],"glow":[{"p":[28.384,2.1,28.384],"size":[7.0,3.8,0.05],"color":"#ffc27a","radiance":0.9,"rotY":45.0},{"p":[31.354,5.05,31.354],"size":[10.0,0.04,7.0],"color":"#ffd29a","radiance":0.6,"rotY":45.0}],"floods":[{"p":[8.7,7.0,40.0],"target":[20.0,0.0,47.0]}],"lenses":[[8.888,6.884,40.116]]},"bbox":[[-52.22,-1.775,-52.22],[55.083,10.025,55.083]],"footprint":[104,104],"height":30.0,"orbital":false};
// </GENERATED>

export const { meta, asset, studio, load, build } = colonyBuilding({
  id: 'infrastructure',
  DATA,
  meta: {
    name: 'Infrastructure', designation: 'IN-4', gameId: 'INFRASTRUCTURE',
    blurb: 'Colony administration and utilities: four two-storey wings in a cross round a domed command hub with an antenna cluster, a courtyard garden behind the entrance portico, a water tower and utility vessel skids, on a 104 m square slab.',
  },
  // the concept's camera (front-left)
  // v3 paint check: light-paint luminance trimmed to the concept's with the key alone (no paint lift)
  studio: { az: 40, el: 33, dist: 0.85, key: 0.62 },
});
