// Library (LIBRARY) — colony building v1, cqs-fleet style (brief: style-library/styles/cqs-fleet/briefs/buildings.md).
// Concept: style-library/styles/cqs-fleet/images/buildings/library-concept.jpg (approved, correction 35).
// Built by tools/blender/buildings/library.py on the shared kit (bkit.py) with colony_build.py; the runtime is the
// shared colony factory (colony.js): light paint (livery null), building finish preset, generated lights.
import { colonyBuilding } from './colony.js';

// <GENERATED by tools/blender/buildings/colony_build.py: do not edit by hand>
const DATA = {"lights":{"pins":[[-54.85,-0.17,-36.03],[-56.03,-0.17,-34.85],[-54.85,-0.17,34.03],[-56.03,-0.17,32.85],[54.85,-0.17,-36.03],[56.03,-0.17,-34.85],[54.85,-0.17,34.03],[56.03,-0.17,32.85],[-42.0,-0.17,34.05],[-28.0,-0.17,34.05],[-14.0,-0.17,34.05],[0.0,-0.17,34.05],[14.0,-0.17,34.05],[28.0,-0.17,34.05],[42.0,-0.17,34.05],[56.05,-0.17,-22.0],[56.05,-0.17,-8.0],[56.05,-0.17,6.0],[56.05,-0.17,20.0],[-47.4,0.6,17.4],[-47.4,0.6,-29.4],[47.4,0.6,17.4],[47.4,0.6,-29.4],[-11.0,4.45,21.0],[11.0,4.45,21.0],[-8.9,4.85,29.6],[8.9,4.85,29.6],[-18.77,2.7,22.23],[-18.77,2.7,29.77],[-10.23,2.7,22.23],[-10.23,2.7,29.77],[10.23,2.7,22.23],[10.23,2.7,29.77],[18.77,2.7,22.23],[18.77,2.7,29.77],[-42.0,0.95,31.6],[-34.0,0.95,31.6],[-18.0,0.95,31.6],[18.0,0.95,31.6],[34.0,0.95,31.6],[42.0,0.95,31.6],[-53.293,6.82,-33.293],[53.293,6.82,-33.293]],"beacons":[[0.0,50.0,4.0]],"nav":[],"slits":[{"p":[-14.4,2.72,29.5],"u":[1.0,0.0,0.0],"n":[0.0,0.0,1.0],"len":0.6,"width":0.14,"door":true},{"p":[14.6,2.72,29.5],"u":[1.0,0.0,0.0],"n":[0.0,0.0,1.0],"len":0.6,"width":0.14,"door":true}],"windows":[{"p":[6.45,21.1,-26.96],"n":[0.0,0.0,-1.0],"size":[1.0,2.2]},{"p":[2.15,21.1,-26.96],"n":[0.0,0.0,-1.0],"size":[1.0,2.2]},{"p":[-10.75,21.1,-26.96],"n":[0.0,0.0,-1.0],"size":[1.0,2.2]},{"p":[2.15,27.1,-26.96],"n":[0.0,0.0,-1.0],"size":[1.0,2.2]},{"p":[-2.15,27.1,-26.96],"n":[0.0,0.0,-1.0],"size":[1.0,2.2]},{"p":[-6.45,27.1,-26.96],"n":[0.0,0.0,-1.0],"size":[1.0,2.2]}],"glow":[{"p":[0.0,3.8,21.0],"size":[8.0,0.04,3.0],"color":"#ffc27a","radiance":0.5}],"floods":[],"lenses":[]},"bbox":[[-56.2,-1.62,-36.2],[56.22,31.76,34.22]],"footprint":[112,70],"height":56.0,"orbital":false};
// </GENERATED>

export const { meta, asset, studio, load, build } = colonyBuilding({
  id: 'library',
  DATA,
  meta: {
    name: 'Library', designation: 'LB-1', gameId: 'LIBRARY',
    blurb: 'The colony archive: two stepped, battered stone wings either side of a 46 m portal tower with a tall gold-lit glazed slot, a grand stair up to the entrance podium and lit pylons on the plaza, on a 112 x 70 m slab.',
  },
  // the concept's camera (front-left)
  studio: { az: 22, el: 22, dist: 0.95 },
  // the fal stone reads brown-grey under the detail layer: lift it to the concept's light stone, no metal sheen
  materials: { colony_steppedWing: { colorScale: 1.6, metalness: 0.0 }, colony_portalTower: { colorScale: 1.5, metalness: 0.0 }, colony_monumentPylon: { colorScale: 1.2 } },
});
