// Military Base (MILITARY_BASE) — colony building v1, cqs-fleet style (brief: style-library/styles/cqs-fleet/briefs/buildings.md).
// Concept: style-library/styles/cqs-fleet/images/buildings/military_base-concept.jpg (approved, correction 35).
// Built by tools/blender/buildings/military_base.py on the shared kit (bkit.py) with fal components (armouredHangar,
// commandBunker, guardTower, wallSegment, gateHouse) and colony_build.py; the runtime is the shared colony factory
// (colony.js). The yard's vehicles are the fleet's own V-31 (assets/ships/vehicle.glb, 'mini' tier), instanced here
// (correction 26: show the actual unit; correction 32: reuse the existing model), with their own marker lamps.
import * as THREE from 'three';
import { colonyBuilding } from './colony.js';
import { loadGLB, buildGLBShip } from '../lib/glbship.js';
import * as VEHICLE from '../ships/vehicle.js';

// <GENERATED by tools/blender/buildings/colony_build.py: do not edit by hand>
const DATA = {"lights":{"pins":[[-57.55,-0.17,-45.53],[-59.03,-0.17,-44.05],[-57.55,-0.17,48.53],[-59.03,-0.17,47.05],[57.55,-0.17,-45.53],[59.03,-0.17,-44.05],[57.55,-0.17,48.53],[59.03,-0.17,47.05],[-39.333,-0.17,48.55],[-19.667,-0.17,48.55],[0.0,-0.17,48.55],[19.667,-0.17,48.55],[39.333,-0.17,48.55],[59.05,-0.17,-26.7],[59.05,-0.17,-7.9],[59.05,-0.17,10.9],[59.05,-0.17,29.7],[-56.2,1.2,-42.2],[-56.2,1.2,42.2],[56.2,1.2,-42.2],[56.2,1.2,42.2],[-40.0,6.9,40.2],[-28.0,6.9,40.2],[14.0,6.9,40.2],[26.0,6.9,40.2],[38.0,6.9,40.2],[54.2,6.9,-24.0],[54.2,6.9,-8.0],[54.2,6.9,8.0],[54.2,6.9,24.0],[-46.0,1.0,5.4],[-44.0,7.0,3.0],[-21.0,1.0,5.4],[-23.0,7.0,3.0],[21.0,1.0,5.4],[23.0,7.0,3.0],[46.0,1.0,5.4],[44.0,7.0,3.0],[-32.77,4.1,26.73],[-32.77,4.1,33.27],[-25.23,4.1,26.73],[-25.23,4.1,33.27],[-20.0,8.82,4.8],[20.0,8.82,4.8],[-35.151,8.82,27.151],[33.151,8.82,27.151]],"beacons":[[0.0,22.4,-21.5],[-33.5,13.8,-15.6],[33.5,13.8,-15.6]],"nav":[[1.0,27.4,-22.5]],"slits":[{"p":[-30.4,2.72,33.0],"u":[1.0,0.0,0.0],"n":[0.0,0.0,1.0],"len":0.6,"width":0.14,"door":true}],"windows":[{"p":[-25.54,2.1,31.45],"n":[1.0,0.0,0.0],"size":[1.4,1.0]},{"p":[-25.54,2.1,28.55],"n":[1.0,0.0,0.0],"size":[1.4,1.0]}],"glow":[],"floods":[],"lenses":[]},"bbox":[[-59.2,-1.877,-45.7],[59.22,9.42,53.08]],"footprint":[118,94],"height":22.0,"orbital":false};
// </GENERATED>

// one V-31 on the yard, as in the concept (building frame: ground y = 0, heading in degrees, 0 = +Z). Each instance is
// the 40k-triangle 'mini' V-31: four of them took the phone tier to 267k triangles, one keeps it at ~150k
const VEHICLES = [
  { p: [16.0, 0, 24.0], heading: 62 },
];

let VG = null;
const base = colonyBuilding({
  id: 'military_base',
  DATA,
  meta: {
    name: 'Military Base', designation: 'MB-2', gameId: 'MILITARY_BASE',
    blurb: 'Garrison compound for the ground forces: a 104 x 76 m yard inside buttressed blast walls with a fortified gate and four corner towers, two armoured vehicle hangars, a stepped command bunker with its antenna cluster, and a V-31 on the yard.',
  },
  // the concept's camera: almost square on to the front wall, a little from the left, ~28 deg down
  // v3 paint check: light-paint luminance trimmed to the concept's with the key alone (no paint lift)
  studio: { az: 14, el: 28, sunaz: -20, sunel: 45, dist: 0.9, exposure: 1.1, key: 0.6 },
  extend(group, { palette, library }) {
    if (!VG) return;
    const box = new THREE.Box3().setFromObject(VG.scene);
    const c = box.getCenter(new THREE.Vector3());
    const proto = buildGLBShip(VG, { name: 'vehicle', ...VEHICLE.asset }, { palette, library });
    const targets = group.userData.building.effectTargets;
    for (const [i, v] of VEHICLES.entries()) {
      const g = new THREE.Group();
      for (const ch of proto.children) g.add(ch.clone());
      g.userData.ship = proto.userData.ship;
      const a = THREE.MathUtils.degToRad(v.heading);
      g.position.set(v.p[0] + c.x * Math.cos(a) + c.z * Math.sin(a), v.p[1] + c.y, v.p[2] - c.x * Math.sin(a) + c.z * Math.cos(a));
      g.rotation.y = a;
      g.name = `military_base-vehicle-${i}`;
      group.add(g);
      targets.push(g);
    }
  },
});

export const { meta, asset, studio, build } = base;
/** The building GLB and the reused V-31 GLB. */
export async function load() {
  await Promise.all([base.load(), loadGLB(VEHICLE.asset.glb, 'mini').then((g) => { VG = g; })]);
}
