// Oil Tanks (OIL_TANKS) — colony building v1, cqs-fleet style (brief: style-library/styles/cqs-fleet/briefs/buildings.md).
// Concept: style-library/styles/cqs-fleet/images/buildings/oil_tanks-concept.jpg (approved, correction 35).
// Built by tools/blender/buildings/oil_tanks.py on the shared kit (bkit.py) with colony_build.py; the runtime is the
// shared colony factory (colony.js): light paint (livery null), building finish preset, generated lights.
import { colonyBuilding } from './colony.js';

// <GENERATED by tools/blender/buildings/colony_build.py: do not edit by hand>
const DATA = {"lights":{"pins":[[-34.85,-0.17,-36.03],[-36.03,-0.17,-34.85],[-34.85,-0.17,36.03],[-36.03,-0.17,34.85],[34.85,-0.17,-36.03],[36.03,-0.17,-34.85],[34.85,-0.17,36.03],[36.03,-0.17,34.85],[-18.0,-0.17,36.05],[0.0,-0.17,36.05],[18.0,-0.17,36.05],[36.05,-0.17,-18.0],[36.05,-0.17,0.0],[36.05,-0.17,18.0],[-33.834,9.42,-33.834],[-33.834,9.42,33.834],[33.834,9.42,-33.834],[33.834,9.42,33.834],[-22.933,3.55,34.4],[-11.467,3.55,34.4],[0.0,3.55,34.4],[11.467,3.55,34.4],[22.933,3.55,34.4],[34.4,3.55,22.933],[34.4,3.55,11.467],[34.4,3.55,0.0],[34.4,3.55,-11.467],[34.4,3.55,-22.933],[22.933,3.55,-34.4],[11.467,3.55,-34.4],[0.0,3.55,-34.4],[-11.467,3.55,-34.4],[-22.933,3.55,-34.4],[-34.4,3.55,-22.933],[-34.4,3.55,-11.467],[-34.4,3.55,0.0],[-34.4,3.55,11.467],[-34.4,3.55,22.933],[-18.5,16.4,16.5],[16.5,16.4,-18.5],[-17.5,16.4,-17.5],[4.4,7.9,8.6],[4.4,7.9,17.4],[21.6,7.9,8.6],[21.6,7.9,17.4],[4.0,5.82,19.0]],"beacons":[[13.0,9.0,13.0]],"nav":[],"slits":[],"windows":[],"glow":[],"floods":[],"lenses":[]},"bbox":[[-36.2,-1.775,-36.2],[40.081,9.64,40.081]],"footprint":[72,72],"height":16.0,"orbital":false};
// </GENERATED>

export const { meta, asset, studio, load, build } = colonyBuilding({
  id: 'oil_tanks',
  DATA,
  meta: {
    name: 'Oil Tanks', designation: 'OT-3', gameId: 'OIL_TANKS',
    blurb: 'Bulk liquid fuel storage: three 30 m floating-roof tanks in a concrete bund with corner lamp pylons, a pump house and a ground pipe manifold on an 72 x 72 m slab.',
  },
  // the concept's camera: on the diagonal, ~29 deg down; key from the front-left
  studio: { az: 45, el: 25, sunaz: 15, sunel: 42, dist: 1.0 },
});
