// Processing Plant (PROCESSING_PLANT) — colony building v1, cqs-fleet style (brief: style-library/styles/cqs-fleet/briefs/buildings.md).
// Concept: style-library/styles/cqs-fleet/images/buildings/processing_plant-concept.jpg (approved, correction 35).
// Built by tools/blender/buildings/processing_plant.py on the shared kit (bkit.py) with colony_build.py; the runtime is the
// shared colony factory (colony.js): light paint (livery null), building finish preset, generated lights.
import { colonyBuilding } from './colony.js';

// <GENERATED by tools/blender/buildings/colony_build.py: do not edit by hand>
const DATA = {"lights":{"pins":[[-34.85,-0.17,-38.03],[-36.03,-0.17,-36.85],[-34.85,-0.17,38.03],[-36.03,-0.17,36.85],[34.85,-0.17,-38.03],[36.03,-0.17,-36.85],[34.85,-0.17,38.03],[36.03,-0.17,36.85],[-18.0,-0.17,38.05],[0.0,-0.17,38.05],[18.0,-0.17,38.05],[36.05,-0.17,-19.0],[36.05,-0.17,0.0],[36.05,-0.17,19.0],[-16.158,0.9,24.95],[-23.0,0.9,28.9],[-29.842,0.9,24.95],[-29.842,0.9,17.05],[-23.0,0.9,13.1],[-16.158,0.9,17.05],[2.842,0.9,12.95],[-4.0,0.9,16.9],[-10.842,0.9,12.95],[-10.842,0.9,5.05],[-4.0,0.9,1.1],[2.842,0.9,5.05],[-11.158,0.9,-9.05],[-18.0,0.9,-5.1],[-24.842,0.9,-9.05],[-24.842,0.9,-16.95],[-18.0,0.9,-20.9],[-11.158,0.9,-16.95],[-34.4,9.8,34.0],[-29.4,9.8,34.0],[-34.4,9.8,-29.0],[-29.4,9.8,-29.0],[28.673,13.6,-16.336],[20.664,13.6,-8.327],[9.336,13.6,-8.327],[1.327,13.6,-16.336],[1.327,13.6,-27.664],[9.336,13.6,-35.673],[20.664,13.6,-35.673],[28.673,13.6,-27.664],[13.8,10.4,1.8],[13.8,10.4,28.2],[30.2,10.4,1.8],[30.2,10.4,28.2],[34.293,7.32,-35.793],[-34.293,7.32,35.793],[34.293,7.32,35.793]],"beacons":[[22.0,12.4,9.0]],"nav":[],"slits":[],"windows":[],"glow":[],"floods":[{"p":[-28.2,8.5,0.0],"target":[-8.0,0.0,16.0]}],"lenses":[[-28.014,8.422,0.147]]},"bbox":[[-36.2,-1.775,-38.2],[39.083,25.63,41.083]],"footprint":[72,76],"height":33.0,"orbital":false};
// </GENERATED>

export const { meta, asset, studio, load, build } = colonyBuilding({
  id: 'processing_plant',
  DATA,
  meta: {
    name: 'Processing Plant', designation: 'PP-3', gameId: 'PROCESSING_PLANT',
    blurb: 'Ore and volatiles processing: three banded process vessels with cobalt bands and stepped heads, a low round storage tank, an armoured plant block, a steel pipe gallery and elbowed transfer lines on a 74 x 80 m slab.',
  },
  // the concept's camera: front-left, ~28 deg down; key from the front-left
  studio: { az: 50, el: 24, sunaz: 20, sunel: 42, dist: 1.0 },
});
