// Radio Telescope (RADIO_TELESCOPE) — colony building v1, cqs-fleet style (brief: style-library/styles/cqs-fleet/briefs/buildings.md).
// Concept: style-library/styles/cqs-fleet/images/buildings/radio_telescope-concept.jpg (approved, correction 35).
// Built by tools/blender/buildings/radio_telescope.py on the shared kit (bkit.py) with colony_build.py; the runtime is the
// shared colony factory (colony.js): light paint (livery null), building finish preset, generated lights.
import { colonyBuilding } from './colony.js';

// <GENERATED by tools/blender/buildings/colony_build.py: do not edit by hand>
const DATA = {"lights":{"pins":[[-20.05,-0.17,-29.03],[-21.03,-0.17,-28.05],[-20.05,-0.17,29.03],[-21.03,-0.17,28.05],[26.05,-0.17,-29.03],[27.03,-0.17,-28.05],[26.05,-0.17,29.03],[27.03,-0.17,28.05],[-9.0,-0.17,29.05],[3.0,-0.17,29.05],[15.0,-0.17,29.05],[27.05,-0.17,-14.5],[27.05,-0.17,0.0],[27.05,-0.17,14.5],[-13.22,10.1,-15.22],[-13.22,10.1,15.22],[13.22,10.1,-15.22],[13.22,10.1,15.22],[-8.27,6.1,14.73],[-8.27,6.1,22.27],[4.27,6.1,14.73],[4.27,6.1,22.27],[4.23,11.6,14.73],[4.23,11.6,20.27],[9.77,11.6,14.73],[9.77,11.6,20.27],[-0.27,5.1,-20.27],[-0.27,5.1,-14.73],[6.27,5.1,-20.27],[6.27,5.1,-14.73],[26.207,6.82,28.207],[24.793,6.82,-26.793],[12.6,1.0,14.0],[12.6,1.0,-14.0]],"beacons":[[7.0,16.1,18.0]],"nav":[],"slits":[{"p":[4.9,2.72,-15.0],"u":[-1.0,0.0,0.0],"n":[0.0,0.0,-1.0],"len":0.6,"width":0.14,"door":true},{"p":[13.32,4.6,10.75],"u":[0.0,1.0,0.0],"n":[1.0,0.0,0.0],"len":1.0,"width":0.16,"door":false},{"p":[13.32,4.6,4.05],"u":[0.0,1.0,0.0],"n":[1.0,0.0,0.0],"len":1.0,"width":0.16,"door":false},{"p":[13.0,2.72,-6.1],"u":[0.0,0.0,-1.0],"n":[1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true},{"p":[0.6,2.72,22.0],"u":[1.0,0.0,0.0],"n":[0.0,0.0,1.0],"len":0.6,"width":0.14,"door":true},{"p":[6.0,2.72,-17.9],"u":[0.0,0.0,-1.0],"n":[1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true}],"windows":[{"p":[3.96,2.1,16.8],"n":[1.0,0.0,0.0],"size":[1.2,1.0]},{"p":[5.8,6.3,19.96],"n":[0.0,0.0,1.0],"size":[1.0,1.0]},{"p":[8.2,10.1,19.96],"n":[0.0,0.0,1.0],"size":[1.0,1.0]}],"glow":[],"floods":[{"p":[-13.55,8.5,-6.0],"target":[-24.0,0.0,-10.0]}],"lenses":[[-13.736,8.349,-6.071]]},"bbox":[[-21.2,-1.677,-29.2],[33.079,15.92,29.22]],"footprint":[48,58],"height":54.0,"orbital":false};
// </GENERATED>

export const { meta, asset, studio, load, build } = colonyBuilding({
  id: 'radio_telescope',
  DATA,
  meta: {
    name: 'Radio Telescope', designation: 'RT-7', gameId: 'RADIO_TELESCOPE',
    blurb: 'Deep-space listening post: a 42 m panelled dish with its feed cabin on three lattice legs, carried by a yoke on a buttressed azimuth drum, over a chamfered armoured base with crew and roller doors, a stair tower and cryo plant, on a 48 x 58 m slab.',
  },
  // the concept's camera: well round to the +X side (the door face), low (~8 deg); key from the front-left
  // v3 paint check: light-paint luminance trimmed to the concept's with the key alone (no paint lift)
  studio: { az: 62, el: 8, sunaz: 60, sunel: 22, key: 1.15 },   // v3: a low key from the camera side lights the yoke and drum under the dish (at 55 deg up the dish shaded them)
});
