// Residence (RESIDENCE) — colony building v1, cqs-fleet style (brief: style-library/styles/cqs-fleet/briefs/buildings.md).
// Concept: style-library/styles/cqs-fleet/images/buildings/residence-concept.jpg (approved, correction 35).
// Built by tools/blender/buildings/residence.py on the shared kit (bkit.py) with colony_build.py; the runtime is the
// shared colony factory (colony.js): light paint (livery null), building finish preset, generated lights.
import { colonyBuilding } from './colony.js';

// <GENERATED by tools/blender/buildings/colony_build.py: do not edit by hand>
const DATA = {"lights":{"pins":[[-49.05,-0.17,-36.03],[-50.03,-0.17,-35.05],[-49.05,-0.17,36.03],[-50.03,-0.17,35.05],[49.05,-0.17,-36.03],[50.03,-0.17,-35.05],[49.05,-0.17,36.03],[50.03,-0.17,35.05],[-35.714,-0.17,36.05],[-21.429,-0.17,36.05],[-7.143,-0.17,36.05],[7.143,-0.17,36.05],[21.429,-0.17,36.05],[35.714,-0.17,36.05],[50.05,-0.17,-21.6],[50.05,-0.17,-7.2],[50.05,-0.17,7.2],[50.05,-0.17,21.6],[-26.3,2.0,10.2],[-16.8,2.0,8.2],[-5.8,2.0,6.2],[6.7,2.0,8.7],[-24.3,2.0,20.2],[-12.8,2.0,20.7],[-0.8,2.0,20.7],[10.7,2.0,20.2],[-3.3,2.0,-5.3],[4.2,2.0,-13.8],[-11.8,2.0,-2.3],[42.73,7.1,-33.27],[42.73,7.1,-22.73],[49.27,7.1,-33.27],[49.27,7.1,-22.73],[-48.77,4.1,23.73],[-48.77,4.1,32.27],[-43.23,4.1,23.73],[-43.23,4.1,32.27],[-48.434,5.32,34.434],[48.434,5.32,34.434],[48.434,5.32,-34.434],[24.0,5.32,33.8],[-28.0,5.32,33.8]],"beacons":[[-22.0,32.4,-14.0],[1.0,26.568,-9.0],[32.0,29.808,6.0]],"nav":[],"slits":[{"p":[49.32,2.8,-26.15],"u":[0.0,1.0,0.0],"n":[1.0,0.0,0.0],"len":1.0,"width":0.16,"door":false},{"p":[49.32,2.8,-30.05],"u":[0.0,1.0,0.0],"n":[1.0,0.0,0.0],"len":1.0,"width":0.16,"door":false},{"p":[-45.9,2.72,32.0],"u":[1.0,0.0,0.0],"n":[0.0,0.0,1.0],"len":0.6,"width":0.14,"door":true}],"windows":[],"glow":[],"floods":[],"lenses":[]},"bbox":[[-50.2,-1.677,-36.2],[53.079,11.077,39.079]],"footprint":[100,72],"height":33.0,"orbital":false};
// </GENERATED>

export const { meta, asset, studio, load, build } = colonyBuilding({
  id: 'residence',
  DATA,
  meta: {
    name: 'Residence', designation: 'HB-9', gameId: 'RESIDENCE',
    blurb: 'Colony housing: three curved ten-storey apartment blocks with continuous balconies, teal accent panels and roof gardens round a courtyard garden, a two-storey podium of entrances along the street, on a 100 x 72 m slab.',
  },
  // the concept's camera: front-left, ~33 deg down
  // v3: key from the front-right, high: the courtyard balcony faces read light like the concept's (the default
  // front-left key left them in shadow); the re-imaged block's lit windows (component.py --hot 0.6 --hot-sat 0.4) a little brighter
  // v3 paint check: light-paint luminance trimmed to the concept's with the key alone (no paint lift)
  studio: { az: 31, el: 32, sunaz: 20, sunel: 40, dist: 0.9, key: 0.6 },
  materials: { colony_curvedTerrace: { emissiveBoost: 1.8 } },
});
