// Planetside SHIPYARD (BuildingEnum.SHIPYARD) — v1 remodel, cqs-fleet style.
// Concept: style-library/styles/cqs-fleet/images/shipyard-r3-A-fixed.jpg (r3 A, corrections 24-28): one dominant dark
// portal gantry "01" straddling a single berth, two slim luffing cranes behind it, two light-painted workshop halls on
// each side, crane runways, flood masts, amber lamps, trucks, containers, forklifts, scaffolds and crew; dusk.
//
// The yard GLB (assets/buildings/shipyard.glb) is built by tools/blender/buildings/ (yard_kit.py parts, shipyard.py
// own geometry, shipyard_spec.py placements, assemble.py) in the YARD frame: metres, ground y = 0, +Z front (the
// bow end of the berth), +X left, origin at the centre of the berth floor. Node 'hull' = the yard's own geometry
// (ground, rails, the DD-12's procedural ring frames and keel, the module on the gantry), 'parts_*' = kit parts.
//
// The ship in the berth is the REAL DD-12 (corrections 26, 32): assets/ships/destroyer.glb is instanced at load through
// the fleet's own ship registry (buildShip('destroyer'): same livery, finish and lights) and cut back to its build
// state here, not baked into the yard GLB: forward of CUT.forward plated and complete; midships cut open to its
// frames (only the lower plating strakes stay, higher toward the bow); aft of CUT.aft no plating at all (the bare
// keel and the octagonal ring frames in the yard GLB follow the hull's measured sections). The cut faces show a dark
// primer inner skin. The spare drive bell on its cradle is the kit bell-XL at the destroyer's own centre-bell scale.
//
// Lights (STYLE.md Installations, lighting-standard F6/F10/F17): amber pins at block corners, gantry and crane
// bogies and on lamp bollards (0.3 m), slow amber beacons on the crab and the crane A-frames, red obstruction
// lights at the gantry and jib tops (the only `lights[]`), door lamps (0.6 x 0.14 m bars) over every crew door,
// amber bars at the gantry leg heads and the big hall doors, lit cab and office windows behind real kit glass, warm
// light in the open hall doors, and six flood masts: kit floodlights with lit lenses and a real spot light each.
// Studio hint `studio` (dusk): the building view dims the showcase rig (see README-shipyard.md, Integration).
import * as THREE from 'three';
import { loadGLB, buildGLBShip } from '../lib/glbship.js';
import { loadShips, buildShip } from '../ships/index.js';

export const meta = {
  name: 'Shipyard',
  designation: 'SY-1',
  gameId: 'SHIPYARD',
  blurb: 'Planetside yard where the fleet\'s non-warp ships are built and fitted out: a 250 m berth under the 95 m portal gantry "01", two luffing cranes on their runway, four light-clad workshop halls, flood masts and the busy apron round them. In the berth: a Bastion-class destroyer DD-12 part-built, its bow plated, midships open to the frames as the gantry lowers a deckhouse module, the stern still bare keel and ring frames.',
};

// <GENERATED by tools/blender/buildings/shipyard_spec.py: do not edit by hand>
const DATA = {"shipT":[0.0,38.8,10.0],"cut":{"forward":20.0,"aft":-34.0,"step":-6.0,"plateAft":-24.0,"plateFwd":-17.0},"keelBlockMin":1.637,"lights":{"pins":[[-50.2,6.4,-24.9],[-50.2,6.4,24.9],[50.2,6.4,-24.9],[50.2,6.4,24.9],[-55.8,105.7,-8.1],[-55.8,105.7,8.1],[55.8,105.7,-8.1],[55.8,105.7,8.1],[61.05,2.8,-52.1],[61.05,2.8,-37.9],[74.95,2.8,-52.1],[74.95,2.8,-37.9],[63.9,21.3,-43.4],[61.05,2.8,-111.1],[61.05,2.8,-96.9],[74.95,2.8,-111.1],[74.95,2.8,-96.9],[63.658,21.3,-103.28],[-87.9,18.2,-54.9],[-87.9,18.2,-135.1],[-124.1,18.2,-54.9],[-124.1,18.2,-135.1],[-124.1,18.2,-49.1],[-124.1,18.2,31.1],[-87.9,18.2,-49.1],[-87.9,18.2,31.1],[124.1,18.2,49.1],[124.1,18.2,-31.1],[87.9,18.2,49.1],[87.9,18.2,-31.1],[87.9,18.2,54.9],[87.9,18.2,135.1],[124.1,18.2,54.9],[124.1,18.2,135.1],[-70.9,4.58,86.6],[-69.1,4.58,86.6],[-106.9,4.58,60.6],[-105.1,4.58,60.6],[81.9,4.58,51.4],[80.1,4.58,51.4],[-3.4,4.58,134.9],[-3.4,4.58,133.1],[66.9,4.58,103.4],[65.1,4.58,103.4],[-63.4,2.32,50.0],[-96.0,2.32,37.4],[76.0,2.32,40.6],[19.4,2.32,-124.0],[-28.0,2.32,119.4],[-41.5,1.12,-120.0],[-41.5,1.12,-80.0],[-41.5,1.12,-40.0],[-41.5,1.12,40.0],[-41.5,1.12,80.0],[-41.5,1.12,120.0],[41.5,1.12,-120.0],[41.5,1.12,-80.0],[41.5,1.12,-40.0],[41.5,1.12,40.0],[41.5,1.12,80.0],[41.5,1.12,120.0]],"beacons":[[4.8,115.2,5.2],[-2.8,115.2,-5.2],[71.0,40.25,-45.0],[70.936,40.25,-103.381]],"nav":[[55.6,111.6,0.0],[-55.4,105.9,0.0],[22.5,80.972,-45.0],[30.085,84.397,-111.99]],"slits":[{"p":[-51.76,93.4,-7.0],"u":[0.0,1.0,0.0],"n":[-1.0,0.0,0.0],"len":1.6,"width":0.2,"door":false},{"p":[-51.76,93.4,7.0],"u":[0.0,1.0,0.0],"n":[-1.0,0.0,0.0],"len":1.6,"width":0.2,"door":false},{"p":[51.76,93.4,-7.0],"u":[0.0,1.0,0.0],"n":[1.0,0.0,0.0],"len":1.6,"width":0.2,"door":false},{"p":[51.76,93.4,7.0],"u":[0.0,1.0,0.0],"n":[1.0,0.0,0.0],"len":1.6,"width":0.2,"door":false},{"p":[-95.4,13.0,-135.62],"u":[0.0,1.0,0.0],"n":[0.0,0.0,-1.0],"len":1.4,"width":0.2,"door":false},{"p":[-116.6,13.0,-135.62],"u":[0.0,1.0,0.0],"n":[0.0,0.0,-1.0],"len":1.4,"width":0.2,"door":false},{"p":[-124.12,2.75,-82.0],"u":[0.0,0.0,-1.0],"n":[-1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true},{"p":[-124.12,2.75,-118.0],"u":[0.0,0.0,-1.0],"n":[-1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true},{"p":[-124.12,2.75,-125.5],"u":[0.0,0.0,-1.0],"n":[-1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true},{"p":[-116.6,13.0,31.62],"u":[0.0,1.0,0.0],"n":[0.0,0.0,1.0],"len":1.4,"width":0.2,"door":false},{"p":[-95.4,13.0,31.62],"u":[0.0,1.0,0.0],"n":[0.0,0.0,1.0],"len":1.4,"width":0.2,"door":false},{"p":[-87.88,2.75,-22.0],"u":[0.0,0.0,1.0],"n":[1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true},{"p":[-87.88,2.75,14.0],"u":[0.0,0.0,1.0],"n":[1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true},{"p":[-87.88,2.75,21.5],"u":[0.0,0.0,1.0],"n":[1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true},{"p":[116.6,13.0,-31.62],"u":[0.0,1.0,0.0],"n":[0.0,0.0,-1.0],"len":1.4,"width":0.2,"door":false},{"p":[95.4,13.0,-31.62],"u":[0.0,1.0,0.0],"n":[0.0,0.0,-1.0],"len":1.4,"width":0.2,"door":false},{"p":[87.88,2.75,22.0],"u":[0.0,0.0,-1.0],"n":[-1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true},{"p":[87.88,2.75,-14.0],"u":[0.0,0.0,-1.0],"n":[-1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true},{"p":[87.88,2.75,-21.5],"u":[0.0,0.0,-1.0],"n":[-1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true},{"p":[95.4,13.0,135.62],"u":[0.0,1.0,0.0],"n":[0.0,0.0,1.0],"len":1.4,"width":0.2,"door":false},{"p":[116.6,13.0,135.62],"u":[0.0,1.0,0.0],"n":[0.0,0.0,1.0],"len":1.4,"width":0.2,"door":false},{"p":[124.12,2.75,82.0],"u":[0.0,0.0,1.0],"n":[1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true},{"p":[124.12,2.75,118.0],"u":[0.0,0.0,1.0],"n":[1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true},{"p":[124.12,2.75,125.5],"u":[0.0,0.0,1.0],"n":[1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true}],"windows":[{"p":[-1.4,112.8,5.52],"n":[0.0,0.0,1.0],"size":[1.2,1.0]},{"p":[1.0,112.8,5.52],"n":[0.0,0.0,1.0],"size":[1.2,1.0]},{"p":[3.4,112.8,5.52],"n":[0.0,0.0,1.0],"size":[1.2,1.0]},{"p":[-40.1,92.8,7.82],"n":[0.0,0.0,1.0],"size":[1.6,1.3]},{"p":[-37.9,92.8,7.82],"n":[0.0,0.0,1.0],"size":[1.6,1.3]},{"p":[61.38,19.0,-41.4],"n":[-1.0,0.0,-0.0],"size":[2.0,1.1]},{"p":[62.7,19.0,-40.08],"n":[-0.0,0.0,1.0],"size":[1.6,1.0]},{"p":[60.78,19.0,-101.842],"n":[-0.979,0.0,-0.206],"size":[2.0,1.1]},{"p":[61.799,19.0,-100.279],"n":[-0.206,0.0,0.979],"size":[1.6,1.0]},{"p":[-124.02,4.2,-116.76],"n":[-1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[-124.02,4.2,-120.12],"n":[-1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[-124.02,7.6,-115.64],"n":[-1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[-124.02,7.6,-116.76],"n":[-1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[-124.02,7.6,-117.88],"n":[-1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[-124.02,7.6,-120.12],"n":[-1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[-87.98,4.2,11.64],"n":[1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[-87.98,4.2,12.76],"n":[1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[-87.98,4.2,15.0],"n":[1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[-87.98,4.2,17.24],"n":[1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[-87.98,4.2,18.36],"n":[1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[-87.98,7.6,12.76],"n":[1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[-87.98,7.6,15.0],"n":[1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[-87.98,7.6,16.12],"n":[1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[-87.98,7.6,18.36],"n":[1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[87.98,4.2,-13.88],"n":[-1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[87.98,4.2,-16.12],"n":[-1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[87.98,4.2,-17.24],"n":[-1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[87.98,7.6,-11.64],"n":[-1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[87.98,7.6,-13.88],"n":[-1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[124.02,4.2,116.76],"n":[1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[124.02,4.2,120.12],"n":[1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[124.02,4.2,122.36],"n":[1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[124.02,7.6,115.64],"n":[1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[124.02,7.6,116.76],"n":[1.0,0.0,0.0],"size":[1.0,1.2],"office":true},{"p":[124.02,7.6,117.88],"n":[1.0,0.0,0.0],"size":[1.0,1.2],"office":true}],"glow":[{"p":[-106.0,2.75,-127.62],"n":[0.0,0.0,-1.0],"size":[19.0,4.4]},{"p":[-106.0,2.75,23.62],"n":[0.0,0.0,1.0],"size":[19.0,4.4]},{"p":[106.0,2.75,-23.62],"n":[0.0,0.0,-1.0],"size":[19.0,4.4]},{"p":[106.0,2.75,127.62],"n":[0.0,0.0,1.0],"size":[19.0,4.4]}],"floods":[{"p":[-55.1,31.1,-80.0],"target":[-14.0,0.0,-62.0]},{"p":[-55.1,31.1,20.0],"target":[-14.0,0.0,18.0]},{"p":[-55.1,31.1,100.0],"target":[-14.0,0.0,80.0]},{"p":[55.1,31.1,-70.0],"target":[14.0,0.0,-53.0]},{"p":[55.1,31.1,30.0],"target":[14.0,0.0,27.0]},{"p":[55.1,31.1,104.0],"target":[14.0,0.0,83.6]}],"lenses":[[-55.49,31.2,-79.28],[-55.49,31.2,-80.0],[-55.49,31.2,-80.72],[-55.49,30.35,-79.28],[-55.49,30.35,-80.0],[-55.49,30.35,-80.72],[-55.49,31.2,20.72],[-55.49,31.2,20.0],[-55.49,31.2,19.28],[-55.49,30.35,20.72],[-55.49,30.35,20.0],[-55.49,30.35,19.28],[-55.49,31.2,100.72],[-55.49,31.2,100.0],[-55.49,31.2,99.28],[-55.49,30.35,100.72],[-55.49,30.35,100.0],[-55.49,30.35,99.28],[55.49,31.2,-70.72],[55.49,31.2,-70.0],[55.49,31.2,-69.28],[55.49,30.35,-70.72],[55.49,30.35,-70.0],[55.49,30.35,-69.28],[55.49,31.2,29.28],[55.49,31.2,30.0],[55.49,31.2,30.72],[55.49,30.35,29.28],[55.49,30.35,30.0],[55.49,30.35,30.72],[55.49,31.2,103.28],[55.49,31.2,104.0],[55.49,31.2,104.72],[55.49,30.35,103.28],[55.49,30.35,104.0],[55.49,30.35,104.72]]}};
// </GENERATED>

export const asset = {
  glb: './assets/buildings/shipyard.glb',
  generator: 'tools/blender/buildings/ (yard_kit.py, shipyard.py, shipyard_spec.py) + tools/blender/assemble.py',
  concept: '../style-library/styles/cqs-fleet/images/shipyard-r3-A-fixed.jpg',
  rotate: [0, 0, 0],
  hullNodes: ['hull'],
  // buildings keep their light concept paint (correction 27): no livery repaint; the fleet's PATINA detail layer and
  // worn finish (finish.js) still apply, so the yard shades like the ships
  livery: null,
  detail: { set: 'hull', tile: 6, normalStrength: 0.45, roughAmount: 0.35, cavity: 0.15 },
};

// dusk studio: the showcase rig dimmed, a warmer, lower key (applied by the building view, README Integration)
export const studio = { exposure: 1.25, key: 0.42, fill: 0.55, rim: 0.5, kick: 0.6, env: 0.6, lightscapeGain: 1.3 };

const C = {
  amber: 'amber', pin: 0.3, beacon: { size: 0.3, pulse: 3.6 }, obstruction: 0.4,
  window: { color: '#ffd29a', radiance: 1.35 }, office: { color: '#ffe2b8', radiance: 1.1 },
  glow: { color: '#ffb766', radiance: 0.42 }, lens: { color: '#fff1dc', radiance: 5.0, size: [0.42, 0.05, 0.26] },
  flood: { color: '#ffe6c4', intensity: 9000, distance: 220, angle: 46, penumbra: 0.65 },
};

/** Yard-frame light specs (buildGLBShip cfg fields) from the generated DATA. */
function lightCfg() {
  const L = DATA.lights || {};
  const patterns = [];
  if (L.pins?.length) patterns.push({ points: L.pins, color: C.amber, size: C.pin, intensity: 1.0, keep: true });
  if (L.beacons?.length) patterns.push({ points: L.beacons, color: C.amber, size: C.beacon.size, intensity: 1.0, pulse: C.beacon.pulse, keep: true });
  for (const s of L.slits || []) {
    patterns.push(s.door
      ? { slit: s.p, u: s.u, n: s.n, len: 0.6, width: 0.14, radiance: 1.4, color: C.amber }
      : { slit: s.p, u: s.u, n: s.n, len: s.len, width: s.width ?? 0.2, radiance: 1.6, color: C.amber, keep: true });
  }
  const box = (p, n, w, h, t = 0.04, lift = 0.03) => {
    // an axis-aligned glow box on a face with normal n (windows face +-X, +-Z or up)
    const ax = Math.abs(n[0]) > Math.abs(n[2]) ? 'x' : 'z';
    const size = ax === 'x' ? [t, h, w] : [w, h, t];
    return { p: [p[0] + n[0] * lift, p[1] + n[1] * lift, p[2] + n[2] * lift], size };
  };
  const fixtures = [
    ...(L.windows || []).map((w) => ({ ...box(w.p, w.n, w.size[0], w.size[1]), color: (w.office ? C.office : C.window).color, radiance: (w.office ? C.office : C.window).radiance })),
    ...(L.glow || []).map((g) => ({ ...box(g.p, g.n, g.size[0], g.size[1], 0.05, 0.05), color: C.glow.color, radiance: C.glow.radiance })),
    ...(L.lenses || []).map((p) => ({ p, size: C.lens.size, color: C.lens.color, radiance: C.lens.radiance })),
  ];
  const interiorLights = (L.floods || []).map((f) => ({ kind: 'spot', p: f.p, target: f.target, color: C.flood.color, intensity: C.flood.intensity,
    distance: C.flood.distance, angle: C.flood.angle, penumbra: C.flood.penumbra, decay: 2 }));
  const lights = (L.nav || []).map((p) => ({ p, color: 'red', size: C.obstruction }));
  return { lightscape: { seed: 61, patterns }, fixtures, interiorLights, lights };
}

const shift = (p, c) => [p[0] - c.x, p[1] - c.y, p[2] - c.z];
/** Every yard-frame position of a cfg moved by -c (buildGLBShip centres the GLB on its bbox). */
function shiftCfg(cfg, c) {
  const out = { ...cfg };
  out.lights = cfg.lights.map((l) => ({ ...l, p: shift(l.p, c) }));
  out.fixtures = cfg.fixtures.map((f) => ({ ...f, p: shift(f.p, c) }));
  out.interiorLights = cfg.interiorLights.map((l) => ({ ...l, p: shift(l.p, c), ...(l.target ? { target: shift(l.target, c) } : {}) }));
  out.lightscape = { ...cfg.lightscape, patterns: cfg.lightscape.patterns.map((q) => ({ ...q, ...(q.points ? { points: q.points.map((p) => shift(p, c)) } : {}), ...(q.slit ? { slit: shift(q.slit, c) } : {}) })) };
  return out;
}

// ---- the DD-12's build state: CPU clip of the instanced ship's geometry (model frame) ----------------------------------
// keep regions (union of convex sets, each a list of half-spaces { n, d }: keep where n . p <= d), MODEL frame
function keepRegions(cut) {
  const P = (x, y, z, d) => ({ n: [x, y, z], d });
  return [
    [P(0, 0, -1, -cut.forward)],                                                              // z >= forward
    [P(0, 0, 1, cut.forward), P(0, 0, -1, -cut.step), P(0, 1, 0, cut.plateFwd)],              // step <= z < forward, y <= plateFwd
    [P(0, 0, 1, cut.step), P(0, 0, -1, -cut.aft), P(0, 1, 0, cut.plateAft)],                  // aft <= z < step, y <= plateAft
  ];
}
const inside = (r, p) => r.every((h) => h.n[0] * p[0] + h.n[1] * p[1] + h.n[2] * p[2] <= h.d + 1e-5);

/** Clip a geometry (positions in `toModel` space) to the keep regions; returns a new non-indexed geometry or null. */
function clipGeometry(geom, toModel, regions) {
  const g = geom.index ? geom.toNonIndexed() : geom;
  const names = Object.keys(g.attributes);
  const attrs = names.map((k) => g.attributes[k]);
  const sizes = attrs.map((a) => a.itemSize);
  const stride = sizes.reduce((a, b) => a + b, 0);
  const pos = g.attributes.position;
  const n = pos.count;
  const mp = new Float32Array(n * 3);
  const v = new THREE.Vector3();
  for (let i = 0; i < n; i++) { v.fromBufferAttribute(pos, i).applyMatrix4(toModel); mp[i * 3] = v.x; mp[i * 3 + 1] = v.y; mp[i * 3 + 2] = v.z; }
  const vert = (i) => { const o = new Float32Array(stride + 3); let k = 0; attrs.forEach((a, j) => { for (let c = 0; c < sizes[j]; c++) o[k++] = a.array[i * sizes[j] + c]; }); o[stride] = mp[i * 3]; o[stride + 1] = mp[i * 3 + 1]; o[stride + 2] = mp[i * 3 + 2]; return o; };
  const out = [];
  const mpOf = (q) => [q[stride], q[stride + 1], q[stride + 2]];
  const dist = (h, q) => h.n[0] * q[stride] + h.n[1] * q[stride + 1] + h.n[2] * q[stride + 2] - h.d;
  const lerpV = (a, b, t) => { const o = new Float32Array(stride + 3); for (let k = 0; k < stride + 3; k++) o[k] = a[k] + (b[k] - a[k]) * t; return o; };
  let kept = 0;
  for (let t = 0; t < n; t += 3) {
    const tri = [vert(t), vert(t + 1), vert(t + 2)];
    for (const r of regions) {
      if (tri.every((q) => inside(r, mpOf(q)))) { out.push(...tri); kept++; break; }
      let poly = tri;
      for (const h of r) {
        if (poly.length < 3) break;
        const next = [];
        for (let i = 0; i < poly.length; i++) {
          const a = poly[i], b = poly[(i + 1) % poly.length];
          const da = dist(h, a), db = dist(h, b);
          if (da <= 0) next.push(a);
          if ((da < 0 && db > 0) || (da > 0 && db < 0)) next.push(lerpV(a, b, da / (da - db)));
        }
        poly = next;
      }
      for (let i = 1; i + 1 < poly.length; i++) out.push(poly[0], poly[i], poly[i + 1]);
    }
  }
  if (!out.length) return null;
  const res = new THREE.BufferGeometry();
  let off = 0;
  names.forEach((k, j) => {
    const arr = new Float32Array(out.length * sizes[j]);
    out.forEach((q, i) => { for (let c = 0; c < sizes[j]; c++) arr[i * sizes[j] + c] = q[off + c]; });
    const src = attrs[j];
    res.setAttribute(k, new THREE.BufferAttribute(src.array instanceof Float32Array ? arr : new src.array.constructor(arr), sizes[j], src.normalized));
    off += sizes[j];
  });
  return res;
}

const INNER = new THREE.MeshStandardMaterial({ color: '#1b1d20', roughness: 0.85, metalness: 0.1, side: THREE.BackSide });

/** Cut an instanced DD-12 (buildShip clone) back to its build state, in place. */
function buildState(ship, cut) {
  const model = ship.children[0];
  ship.updateMatrixWorld(true);
  // a mesh's matrix into the model's local space, which is the destroyer GLB's own (MODEL) frame: glbship centres the
  // model by its position (-centre), so the local space under it is unshifted
  const toModelOf = (m) => new THREE.Matrix4().copy(model.matrixWorld).invert().multiply(m.matrixWorld);
  const regions = keepRegions(cut);
  const meshes = [];
  model.traverse((o) => { if (o.isMesh) meshes.push(o); });
  let before = 0, after = 0;
  for (const m of meshes) {
    const M = toModelOf(m);
    before += (m.geometry.index ? m.geometry.index.count : m.geometry.attributes.position.count) / 3;
    const g = clipGeometry(m.geometry, M, regions);
    if (!g) { m.visible = false; m.geometry = new THREE.BufferGeometry(); continue; }
    m.geometry = g;
    after += g.attributes.position.count / 3;
    // the cut leaves the plating open: its inner face in dark primer
    const inner = new THREE.Mesh(g, INNER);
    inner.name = `${m.name || 'mesh'}-inner`;
    inner.castShadow = false; inner.receiveShadow = true;
    inner.userData.inner = true;
    m.add(inner);
  }
  return { before: Math.round(before), after: Math.round(after) };
}

let GLTF = null;
/** Load the yard GLB and the destroyer (through the ship registry). */
export async function load() {
  GLTF = await loadGLB(asset.glb);
  await loadShips(['destroyer']);
}

/**
 * Build the yard: a Group in the YARD frame (ground at y = 0). userData.ship carries the yard's envelope and lights
 * (the effects.js contract); userData.building = { yard, ship, effectTargets, buildState }.
 */
export function build(palette, { library = {} } = {}) {
  if (!GLTF) throw new Error('shipyard: call load() first');
  const raw = new THREE.Box3().setFromObject(GLTF.scene);
  const centre = raw.getCenter(new THREE.Vector3());
  const cfg = shiftCfg({ name: 'shipyard', ...asset, length: raw.getSize(new THREE.Vector3()).z, ...lightCfg() }, centre);
  const yard = buildGLBShip(GLTF, cfg, { palette, library });
  yard.position.copy(centre); // back to the yard frame
  const rec = yard.userData.ship;
  for (const k of ['min', 'max', 'center']) rec.envelope[k].add(centre);
  rec.scaleCorrection = 1;

  // the DD-12, instanced from the fleet registry, then cut to its build state
  const ship = buildShip('destroyer', palette);
  const src = ship.userData.ship;
  ship.scale.setScalar(1); // the GLB's own size: the yard's frames and blocks are built on it
  const model = ship.children[0];
  const glbCentre = model.position.clone().negate();
  const T = DATA.shipT || [0, 38.8, 10];
  ship.position.set(T[0] + glbCentre.x, T[1] + glbCentre.y, T[2] + glbCentre.z);
  const stats = buildState(ship, DATA.cut);
  // its lights: only what the plated bow keeps (no drive, no nav lights on a hull in the berth)
  const fwd = (p) => p.z + glbCentre.z >= DATA.cut.forward;
  ship.userData.ship = { ...src, engines: [], lights: [], pins: (src.pins || []).filter((l) => fwd(l.p)), slits: (src.slits || []).filter((s) => fwd(s.p)) };
  ship.traverse((o) => { if (o.name === 'nozzle-glow' || o.name === 'nozzle-lining' || o.name === 'drive-spill') o.visible = false; });

  const group = new THREE.Group();
  group.name = 'shipyard';
  group.add(yard, ship);
  group.userData.ship = rec;
  group.userData.building = { id: 'shipyard', meta, yard, ship, effectTargets: [yard, ship], buildState: stats, studio };
  return group;
}
