// Silicon Depot (SILICON_DEPOT) — colony building v1, cqs-fleet style (brief: style-library/styles/cqs-fleet/briefs/buildings.md).
// Concept: style-library/styles/cqs-fleet/images/buildings/silicon_depot-concept.jpg (approved, correction 35).
// Built by tools/blender/buildings/silicon_depot.py on the shared kit (bkit.py) with colony_build.py; the runtime is the
// shared colony factory (colony.js): light paint (livery null), building finish preset, generated lights.
import { colonyBuilding } from './colony.js';

// <GENERATED by tools/blender/buildings/colony_build.py: do not edit by hand>
const DATA = {"lights":{"pins":[[-31.05,-0.17,-21.03],[-32.03,-0.17,-20.05],[-31.05,-0.17,27.03],[-32.03,-0.17,26.05],[41.05,-0.17,-21.03],[42.03,-0.17,-20.05],[41.05,-0.17,27.03],[42.03,-0.17,26.05],[-13.5,-0.17,27.05],[5.0,-0.17,27.05],[23.5,-0.17,27.05],[42.05,-0.17,-5.0],[42.05,-0.17,11.0],[-25.57,30.1,-14.57],[-25.57,30.1,10.57],[27.57,30.1,-14.57],[27.57,30.1,10.57],[-18.75,26.6,16.2],[-15.45,5.0,15.0],[-15.45,11.0,15.0],[-15.45,17.0,15.0],[-6.25,26.6,16.2],[-2.95,5.0,15.0],[-2.95,11.0,15.0],[-2.95,17.0,15.0],[6.25,26.6,16.2],[9.55,5.0,15.0],[9.55,11.0,15.0],[9.55,17.0,15.0],[18.75,26.6,16.2],[22.05,5.0,15.0],[22.05,11.0,15.0],[22.05,17.0,15.0],[26.63,28.1,-14.37],[26.63,28.1,7.37],[35.37,28.1,-14.37],[35.37,28.1,7.37],[-6.17,35.7,-2.17],[-6.17,35.7,4.17],[2.17,35.7,-2.17],[2.17,35.7,4.17],[25.73,38.1,-4.27],[25.73,38.1,6.27],[34.27,38.1,-4.27],[34.27,38.1,6.27],[34.3,38.2,6.3],[25.7,38.2,6.3],[-29.793,6.82,24.793],[39.793,6.82,24.793],[39.793,6.82,-18.793]],"beacons":[[0.0,43.0,2.0],[32.5,46.8,3.0]],"nav":[],"slits":[{"p":[35.0,2.72,-10.6],"u":[0.0,0.0,-1.0],"n":[1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true}],"windows":[{"p":[18.267,4.1,-13.96],"n":[0.0,0.0,-1.0],"size":[1.2,1.0]},{"p":[12.511,4.1,-13.96],"n":[0.0,0.0,-1.0],"size":[1.2,1.0]},{"p":[-4.756,4.1,-13.96],"n":[0.0,0.0,-1.0],"size":[1.2,1.0]},{"p":[-22.022,4.1,-13.96],"n":[0.0,0.0,-1.0],"size":[1.2,1.0]},{"p":[-3.95,34.05,3.96],"n":[0.0,0.0,1.0],"size":[1.2,0.9]},{"p":[-0.05,34.05,3.96],"n":[0.0,0.0,1.0],"size":[1.2,0.9]}],"glow":[{"p":[18.75,13.0,10.5],"size":[7.0,20.0,0.2],"color":"#ffb766","radiance":0.2},{"p":[34.88,17.5,-4.6],"size":[0.05,15.0,1.4],"color":"#ffc27a","radiance":0.9}],"floods":[{"p":[-25.55,12.0,-10.0],"target":[-30.0,0.0,-20.0]}],"lenses":[[-25.618,11.815,-10.154]]},"bbox":[[-32.2,-1.677,-21.2],[46.09,46.42,33.079]],"footprint":[74,48],"height":38.0,"orbital":false};
// </GENERATED>

export const { meta, asset, studio, load, build } = colonyBuilding({
  id: 'silicon_depot',
  DATA,
  meta: {
    name: 'Silicon Depot', designation: 'SD-4', gameId: 'SILICON_DEPOT',
    blurb: 'Bonded vault for refined silicon: a 30 m monolithic block of four tall bays (three sealed vault doors, one open rack bay of crated stock), violet accent strips, an annex with a tall slot, an armoured entrance porch, roof crown and head tower, on a 76 x 56 m slab.',
  },
  // the concept's camera: front-left, ~18 deg down; key from the front-left so the bay faces and the +X annex read light
  studio: { az: 26, el: 18, sunaz: 15, sunel: 40, dist: 0.78 },
  // the bays' off-white piers: Tripo's paint reads a step darker than the concept's, past the factory's 1.25 lift
  materials: { colony_vaultBay: { colorScale: 1.3, metalness: 0.3 }, colony_rackBay: { colorScale: 1.3, metalness: 0.3 } },
});
