// Steel Mill (STEEL_MILL) — colony building v1, cqs-fleet style (brief: style-library/styles/cqs-fleet/briefs/buildings.md).
// Concept: style-library/styles/cqs-fleet/images/buildings/steel_mill-concept.jpg (approved, correction 35).
// Built by tools/blender/buildings/steel_mill.py on the shared kit (bkit.py) with colony_build.py; the runtime is the
// shared colony factory (colony.js): light paint (livery null), building finish preset, generated lights.
import { colonyBuilding } from './colony.js';

// <GENERATED by tools/blender/buildings/colony_build.py: do not edit by hand>
const DATA = {"lights":{"pins":[[-38.85,-0.17,-50.03],[-40.03,-0.17,-48.85],[-38.85,-0.17,42.03],[-40.03,-0.17,40.85],[38.85,-0.17,-50.03],[40.03,-0.17,-48.85],[38.85,-0.17,42.03],[40.03,-0.17,40.85],[-20.0,-0.17,42.05],[0.0,-0.17,42.05],[20.0,-0.17,42.05],[40.05,-0.17,-31.6],[40.05,-0.17,-13.2],[40.05,-0.17,5.2],[40.05,-0.17,23.6],[37.5,14.0,0.0],[37.5,14.0,26.0],[-38.77,24.1,28.73],[-38.77,24.1,40.27],[-29.23,24.1,28.73],[-29.23,24.1,40.27],[-38.27,7.1,15.73],[-38.27,7.1,24.27],[-31.73,7.1,15.73],[-31.73,7.1,24.27],[30.23,4.6,-13.77],[30.23,4.6,-6.23],[36.77,4.6,-13.77],[36.77,4.6,-6.23],[30.73,3.7,29.23],[30.73,3.7,34.77],[35.27,3.7,29.23],[35.27,3.7,34.77],[37.651,7.82,39.151],[37.651,7.82,-47.151],[-37.651,7.82,39.151]],"beacons":[[-18.0,61.0,26.0]],"nav":[[-16.0,60.4,28.0]],"slits":[{"p":[-36.4,2.72,40.0],"u":[1.0,0.0,0.0],"n":[0.0,0.0,1.0],"len":0.6,"width":0.14,"door":true},{"p":[-29.5,2.72,36.9],"u":[0.0,0.0,-1.0],"n":[1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true},{"p":[-34.9,2.72,24.0],"u":[1.0,0.0,0.0],"n":[0.0,0.0,1.0],"len":0.6,"width":0.14,"door":true},{"p":[36.5,2.72,-8.6],"u":[0.0,0.0,-1.0],"n":[1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true},{"p":[35.0,2.72,31.9],"u":[0.0,0.0,-1.0],"n":[1.0,0.0,0.0],"len":0.6,"width":0.14,"door":true}],"windows":[{"p":[-31.8,14.6,39.96],"n":[0.0,0.0,1.0],"size":[1.2,1.2]},{"p":[-29.54,8.6,31.8],"n":[1.0,0.0,0.0],"size":[1.2,1.2]},{"p":[-32.04,2.1,21.95],"n":[1.0,0.0,0.0],"size":[1.2,1.0]},{"p":[34.95,2.1,-6.54],"n":[0.0,0.0,1.0],"size":[1.2,1.0]},{"p":[36.46,2.1,-11.7],"n":[1.0,0.0,0.0],"size":[1.2,1.0]},{"p":[32.05,2.1,34.46],"n":[0.0,0.0,1.0],"size":[1.2,1.0]}],"glow":[],"floods":[{"p":[24.55,16.0,-12.0],"target":[36.0,0.0,-14.0]},{"p":[24.55,16.0,-36.0],"target":[36.0,0.0,-34.0]}],"lenses":[[24.695,15.798,-12.025],[24.695,15.798,-35.975]]},"bbox":[[-40.2,-1.877,-52.1],[40.22,41.237,42.22]],"footprint":[80,92],"height":61.0,"orbital":false};
// </GENERATED>

export const { meta, asset, studio, load, build } = colonyBuilding({
  id: 'steel_mill',
  DATA,
  meta: {
    name: 'Steel Mill', designation: 'SM-1', gameId: 'STEEL_MILL',
    blurb: 'Integrated steel works: a 60 m blast furnace in its steel tower frame, fed by an inclined skip gallery, a glowing pour bay under an amber overhead crane, two banded stacks and a 72 m clad shed on an 80 x 92 m slab.',
  },
  // the concept's camera: front-left, ~27 deg down
  // key from the front, a little to +X: the long +X shed face and the pour bay are lit as in the concept
  // v3 paint check: light-paint luminance trimmed to the concept's with the key alone (no paint lift)
  studio: { az: 52, el: 22, sunaz: 42, sunel: 44, dist: 0.95, key: 0.6 },
});
