// University (UNIVERSITY) — colony building v1, cqs-fleet style (brief: style-library/styles/cqs-fleet/briefs/buildings.md).
// Concept: style-library/styles/cqs-fleet/images/buildings/university-concept.jpg (approved, correction 35).
// Built by tools/blender/buildings/university.py on the shared kit (bkit.py) with colony_build.py; the runtime is the
// shared colony factory (colony.js): light paint (livery null), building finish preset, generated lights.
import { colonyBuilding } from './colony.js';

// <GENERATED by tools/blender/buildings/colony_build.py: do not edit by hand>
const DATA = {"lights":{"pins":[[-54.95,-0.17,-33.03],[-56.03,-0.17,-31.95],[-54.95,-0.17,33.03],[-56.03,-0.17,31.95],[54.95,-0.17,-33.03],[56.03,-0.17,-31.95],[54.95,-0.17,33.03],[56.03,-0.17,31.95],[-40.0,-0.17,33.05],[-24.0,-0.17,33.05],[-8.0,-0.17,33.05],[8.0,-0.17,33.05],[24.0,-0.17,33.05],[40.0,-0.17,33.05],[56.05,-0.17,-16.5],[56.05,-0.17,0.0],[56.05,-0.17,16.5],[45.6,23.8,11.6],[-30.0,1.7,6.95],[-27.5,1.7,6.95],[24.0,1.7,24.95],[44.0,1.7,24.95],[-53.293,6.82,30.293],[53.293,6.82,30.293],[53.293,6.82,-30.293],[-53.293,6.82,-30.293]],"beacons":[[37.0,27.4,6.0]],"nav":[],"slits":[],"windows":[],"glow":[{"p":[-3.0,5.0,-3.0],"size":[22.0,8.0,20.0],"color":"#ffd8a8","radiance":0.12},{"p":[-20.5,4.0,0.65],"size":[5.8,6.4,0.05],"color":"#ffc27a","radiance":0.8},{"p":[15.5,4.0,6.65],"size":[7.8,6.4,0.05],"color":"#ffc27a","radiance":0.8},{"p":[-9.0,0.92,21.0],"size":[7.6,0.02,3.6],"color":"#7fb6c8","radiance":0.25},{"p":[8.0,0.92,29.5],"size":[4.6,0.02,2.2],"color":"#7fb6c8","radiance":0.25}],"floods":[],"lenses":[]},"bbox":[[-56.2,-1.775,-33.2],[59.083,29.8,36.083]],"footprint":[112,66],"height":30.0,"orbital":false};
// </GENERATED>

export const { meta, asset, studio, load, build } = colonyBuilding({
  id: 'university',
  DATA,
  meta: {
    name: 'University', designation: 'UN-3', gameId: 'UNIVERSITY',
    blurb: 'Colony university: three faceted teaching wings with observatory domes and a radome round a glazed faceted atrium hall, with a terraced front garden, on a 112 x 66 m slab.',
  },
  // the concept's camera (front-left)
  studio: { az: 31, el: 28, dist: 0.9 },
  materials: { colony_facetedWing: { colorScale: 1.35 }, colony_atriumHall: { metalness: 0.3 } },
});
